#!/usr/bin/env bash
# Materialize youtube-music-player/Secrets.swift for a build.
#
# Secrets.swift is in the synchronized source group, so the build won't compile without it,
# but it's .gitignored (it holds the Discord/Spotify client IDs). Locally run.sh copies the
# placeholder example; in CI we do the same, then overlay any real IDs passed as env vars.
#
# Both IDs are OPTIONAL at runtime — Discord Rich Presence and Spotify import simply stay
# dormant when their ID is the placeholder — so a release built with no secrets is fully
# functional minus those two integrations. Set DISCORD_CLIENT_ID / SPOTIFY_CLIENT_ID (from
# GitHub Actions secrets) to bake them in.
set -euo pipefail
cd "$(dirname "$0")/../.."

dest="youtube-music-player/Secrets.swift"
discord="${DISCORD_CLIENT_ID:-YOUR_DISCORD_CLIENT_ID}"
spotify="${SPOTIFY_CLIENT_ID:-YOUR_SPOTIFY_CLIENT_ID}"

# Escape backslash and double-quote so an ID with those chars can't break out of the Swift
# string literal (or get mangled by shell expansion in an interpolating heredoc). printf '%s'
# emits the value literally — no further shell expansion of $ / backticks in it.
swift_escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

{
  echo '// Generated by scripts/release/make-secrets.sh — do not commit (see .gitignore).'
  echo 'enum Secrets {'
  printf '    static let discordClientId = "%s"\n' "$(swift_escape "$discord")"
  printf '    static let spotifyClientID = "%s"\n' "$(swift_escape "$spotify")"
  echo '}'
} > "$dest"

if [[ "$discord" == "YOUR_DISCORD_CLIENT_ID" ]]; then
  echo "make-secrets: Discord ID not set — Rich Presence will be dormant in this build."
else
  echo "make-secrets: baked in Discord client ID."
fi
if [[ "$spotify" == "YOUR_SPOTIFY_CLIENT_ID" ]]; then
  echo "make-secrets: Spotify ID not set — Import from Spotify will be dormant in this build."
else
  echo "make-secrets: baked in Spotify client ID."
fi
